### PR TITLE
Initial PR

### PR DESCRIPTION
**Pull request by petermorgandev**

### CODE REVIEW

**Review by ct-martin — COMMENTED** [review]
@PeterMorganGH this looks great!

I had named the graph view files as `_id.vue` so that [dynamic routes](https://nuxtjs.org/guide/routing#dynamic-routes) (e.g. `github-graphs.com/graph/username` instead of `github-graphs.com/graph?user=username`) could be used later. What are you thoughts on doing this? If you have another plan in mind I'm ready to merge this.

**Comment by ct-martin** [comment]
@PeterMorganGH one more thing, to make sure it's done right could you merge `master` into this branch? I saw you touched some of the front-end JS. (This doesn't have to be in this PR)

**Comment by petermorgandev** [comment]
@ct-martin The file name change was my bad. I was not aware that Nuxt's routing worked that way. I have reverted those changes in a new commit: https://github.com/ct-martin/github-graphs/pull/1/commits/3a0a35e0670ac54369fa681e1e185baa6a480872.

**Comment by ct-martin** [comment]
@PeterMorganGH thanks! :tada:

**Pull request merged**
